const API_URL = 'https://dev.tedooo.com'
const IMPRESSION_DELAY = 1000
const IMPRESSION_TRIGGER_ONCE = false
const IMPRESSION_THRESHOLD = 0.5

export { API_URL, IMPRESSION_DELAY, IMPRESSION_TRIGGER_ONCE, IMPRESSION_THRESHOLD }
