const API_URL = 'https://dev.tedooo.com'
const IMPRESSION_TIMEOUT = 1
const IMPRESSION_MULTIPLE_MODE = false
const IMPRESSION_THRESHOLD = 0.5

export { API_URL, IMPRESSION_TIMEOUT, IMPRESSION_MULTIPLE_MODE, IMPRESSION_THRESHOLD }
